use world; 
SELECT "Hello World" AS message, 123 AS id;
SELECT * FROM City;
SELECT * FROM City WHERE District = 'aceh';
SELECT Name FROM City WHERE CountryCode = 'BFA';
SELECT Name, District FROM City WHERE CountryCode = 'TTO';
SELECT Name AS nm, District AS dist FROM City WHERE CountryCode = 'ARM';
SELECT * FROM City WHERE Name LIKE 'Bor%';
SELECT * FROM City WHERE Name LIKE '%orto%';
SELECT * FROM City WHERE Population < 1000;
SELECT DISTINCT CountryCode FROM City WHERE Population < 1000;
SELECT * FROM City WHERE CountryCode = 'UKR' AND Population > 1000000;
SELECT * FROM City WHERE Population < 200 OR Population > 9500000;
SELECT * FROM City WHERE CountryCode IN ('TJK', 'MRT', 'AND', 'PNG', 'SJM');
SELECT * FROM City WHERE Population BETWEEN 200 AND 700;
SELECT * FROM Country WHERE Population BETWEEN 8000 AND 20000;
SELECT Name FROM Country WHERE IndepYear < 0;
SELECT * FROM Country WHERE IndepYear IS NULL AND Population > 1000000;
SELECT * FROM Country WHERE SurfaceArea < 10 AND LifeExpectancy IS NOT NULL;
